# Generated by Django 4.1.2 on 2023-01-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_pets_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Family',
            new_name='Relatives',
        ),
    ]
