# Generated by Django 4.1.2 on 2023-01-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_category_rename_family_relatives'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
